version: 2

models:

  - name: exemple_model
    description: "Clients ayant effectué des réservations de vols, hôtels et voitures sur la même année"

    columns:
      - name: id_client
        description: "Identifiant unique du client"
        tests:
          - not_null
          - unique

      - name: nom
        tests:
          - not_null

      - name: prenom
        tests:
          - not_null

      - name: annee
        tests:
          - not_null


  - name: stg_clients
    description: "Données nettoyées des clients"

    columns:
      - name: id_client
        tests:
          - not_null
          - unique


  - name: stg_hotels
    description: "Données nettoyées des hôtels"

    columns:
      - name: id_hotel
        tests:
          - not_null
          - unique


  - name: stg_agences
    description: "Données nettoyées des agences"

    columns:
      - name: id_agence_voiture
        tests:
          - not_null
          - unique


  - name: stg_aeroports
    description: "Données nettoyées des aéroports"

    columns:
      - name: id_aeroport
        tests:
          - not_null
          - unique

sources:
  - name: travelcorp
    description: "Données brutes provenant de BigQuery - dataset TravelCorp"

    database: luxevoyages-493908
    schema: TravelCorp

    tables:

      - name: clients
        description: "Table brute des clients"

      - name: hotels
        description: "Table brute des hôtels"

      - name: agences
        description: "Table brute des agences de location"

      - name: aeroports
        description: "Table brute des aéroports"

      - name: reservationsHotels
        description: "Réservations d'hôtels"

      - name: reservationsVoitures
        description: "Réservations de voitures"

      - name: reservationsVols
        description: "Réservations de vols"

      - name: dates
        description: "Table des dates"