version: 2


# SOURCES 
sources:
  - name: techstore
    description: "Données brutes du dataset TechStore"
    database: luxevoyages-493908
    schema: TechStore

    tables:
      - name: Clients
        description: "Table brute des clients"

      - name: Produits
        description: "Table brute des produits"

      - name: Ventes
        description: "Table brute des ventes"

      - name: Dates
        description: "Table des dates"


# STAGING 
models:

  - name: stg_clients
    description: "Nettoyage et préparation des clients"
    columns:
      - name: id_client
        description: "Identifiant du client"
        tests:
          - not_null
          - unique

      - name: nom
        description: "Nom du client"

      - name: segment_client
        description: "Segment du client"

  - name: stg_produits
    description: "Nettoyage des produits"
    columns:
      - name: id_produit
        tests:
          - not_null
          - unique

      - name: nom_produit

      - name: categorie_produit

  - name: stg_ventes
    description: "Nettoyage des ventes"
    columns:
      - name: id_vente
        tests:
          - not_null
          - unique

      - name: id_client
      - name: id_produit
      - name: montant
      - name: date


# DIMENSIONS

  - name: dim_categories
    description: "Table des catégories de produits normalisées"
    columns:
      - name: id_categorie
        tests:
          - not_null
          - unique

      - name: categorie

  - name: dim_produits
    description: "Dimension des produits liée aux catégories"
    columns:
      - name: id_produit
        tests:
          - not_null
          - unique

      - name: id_categorie
        tests:
          - not_null

  - name: dim_segments
    description: "Segments clients normalisés"
    columns:
      - name: id_segment
        tests:
          - not_null
          - unique

      - name: segment

  - name: dim_clients
    description: "Dimension clients liée aux segments"
    columns:
      - name: id_client
        tests:
          - not_null
          - unique

      - name: id_segment
        tests:
          - not_null

# FACT

  - name: fct_ventes
    description: "Table de faits des ventes"
    columns:
      - name: id_vente
        tests:
          - not_null
          - unique

      - name: id_client
        tests:
          - not_null

      - name: id_produit
        tests:
          - not_null

      - name: montant
        tests:
          - not_null

      - name: date